### ISSUE TITLE
Doorbell RF replay example ?

### ISSUE THREAD

**Issue by gbraux** [jglim/CCManager#1]
Hi jglim,

Have you ever published your RF replay attach guide somewhere ?

> RF replay attack - attack fixed-code communication devices such as some gates, doorbells and wireless switches. **I'll be publishing a guide shortly.**

I am playing with the CC1101 and struggling to use it as a generic and easy to use trasmitter (the register stuff is complex ...). That's why a guide about your methodology would have been very interesting, so understand the different steps needed to be able to mimic a signal with a CC1101 ...

Thanks
Guillaume.

**Comment by jglim** [comment]
Hey Guillaume,

I've written a guide but have yet to convert to Markdown (procrastination haha). In the interim, perhaps the PDF version would be ok with you?

[CCManager.pdf](https://github.com/jglim/CCManager/files/612566/CCManager.pdf)

In any case, when you have the hardware & software up, writing the frequency & baud rate will update the registers, and you can view that in under "View/Edit Registers"

Cheers
JG
