### ISSUE TITLE
Disable the CC1101's preamble and sync transmission

### ISSUE THREAD

**Issue by AzInstall** [jglim/CCManager#2]
I just came across your program and only read the intro, but under Limitations, you stated, "I haven't figured a way to disable the CC1101's preamble and sync transmission."

It's been awhile but I believe you do this with:
**MDMCFG2    0x30        // Modem Configuration
MDMCFG1    0x00        // Modem Configuration**

Here is the register descriptions in the datasheet:
[Image 1](https://i.stack.imgur.com/SrkbF.png)
[Image 2](https://i.stack.imgur.com/00eEc.png)

Hope that helps! Also, you can't disable the RX FIFO to be used with the TX FIFO but you can do an asynchronous mode if you can get everything to communicate fast enough.

**Comment by jglim** [comment]
Hey Garrett - thanks for taking your time to open this issue:

I've tested your suggestion and setting MDMCFG2 to 0x30 does the trick! It should be okay to ignore MDMCFG1. I'll put up an update to fix the default registers. 

![ccmanager-mdmcfg2_labeled](https://cloud.githubusercontent.com/assets/1116555/21035356/53bdc778-bdf9-11e6-8026-4e64df5cdd43.png)

Thanks for fixing this! ^_^
